on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project 
        run: |
          mvn -B clean package
      
      # Upload release artifact (the .zip file) manually
      # https://github.com/actions/upload-release-asset/issues/47#issuecomment-659071145
      - name: Create release and upload asset
        uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log("Environment", process.versions);
           
            const { repo: { owner, repo }, sha } = context;
            console.log("Context", { owner, repo, sha });
            
            const short_tag_name = process.env.GITHUB_REF.replace("refs/tags/", ""); 
            console.log("tag_name", process.env.GITHUB_REF);
            console.log("short_tag_name", short_tag_name); 
            
            const release = await github.repos.createRelease({
              owner, repo,
              tag_name: short_tag_name,
              draft: false,
              prerelease: true,
              target_commitish: sha,
              body: "Release generated by GitHub actions"
            });
            
            console.log("Created release", { release });
            
            const fsAsync = require("fs").promises;
            const fsSync = require("fs"); 
            
            const files = await fsAsync.readdir("./target"); 
            console.log("Found files in /target: " + files); 
            
            const zipFile = files.filter(fileName => fileName.includes(".zip"))[0]; 
            const pathToZipFile = "./target/" + zipFile; 
            console.log('Uploading file ', pathToZipFile);
            
            // Determine content-length for header to upload asset
            const getContentLength = filePath => fsSync.statSync(filePath).size;
            const headers = { 'content-type': "application/zip", 'content-length': getContentLength(pathToZipFile) };
            
            console.log("Using headers", headers); 
            
            // Using this example
            // https://github.com/actions/upload-release-asset/blob/main/src/upload-release-asset.js
            // Documented here: https://github.com/octokit/plugin-rest-endpoint-methods.js/blob/master/docs/repos/uploadReleaseAsset.md
            const uploadedReleaseAsset = await github.repos.uploadReleaseAsset({
              url: release.data.upload_url,
              headers,
              name: zipFile,
              data: fsSync.readFileSync(pathToZipFile)
            });            
            
            console.log("Uploaded release asset", { uploadedReleaseAsset }); 

