on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project 
        run: |
          mvn -B clean package
      
      # Upload release artifact (the .zip file) manually
      # https://github.com/actions/upload-release-asset/issues/47#issuecomment-659071145
      - name: Create release and upload asset
        uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log('environment', process.versions);
           
            const { repo: { owner, repo }, sha } = context;
            console.log({ owner, repo, sha });
            
            const release = await github.repos.createRelease({
              owner, repo,
              tag_name: process.env.GITHUB_REF,
              draft: false,
              prerelease: true, 
              target_commitish: sha
            });
            
            console.log('created release', { release });
            
            const fs = require('fs').promises;
            const files = await fs.readdir("."); 
            const zipFile = files.filter(fileName => fileName.includes(".zip"))[0]; 
            console.log('Uploading file ', zipFile);
            
            await github.repos.uploadReleaseAsset({
              owner, repo,
              release_id: release.data.id,
              name: zipFile,
              data: await fs.readFile(`./${zipFile}`)
            });            
            

